---
# tasks file for groups.local

- name: add groups in /etc/groups.local
  become: true
  blockinfile:
     path: /etc/groups.local
     marker: "# {mark} Added by CeR"
     block: |
       {{ project_code }}_vmadmin.eresearch sudo token
       {{ project_code }}_vmuser.eresearch
       {{ project_code }}_rw

- name: run the puppet manually to create the groups on the VM
  become: true
  command: /opt/puppetlabs/bin/puppet agent -t

- name: restore /etc/groups.local 
  become: true
  blockinfile:
     path: /etc/groups.local
     marker: "# {mark} Added by CeR"
     content: ""
