---
# tasks file for groups.local

- name: create file /etc/groups.local
  become: true
  template:
    src: groups.local.j2
    dest: /etc/groups.local
    owner: root
    group: root
    mode: 0644
    force: yes

- name: run puppet to create groups and accounts for members of the groups defined in /etc/groups.local
  become: true
  puppet:
  #command: /opt/puppetlabs/bin/puppet agent -t
