---

# Install dependencies and rescan bus for new disks.
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

# Set up LVM /data partition according to configuration
- include: manage_lvm.yml
  when: ansible_system == "Linux"
  
# Set up permissions on /data folder for sharing among a group
- include: permission.yml
  when: ansible_system == "Linux"
