---

- name: permission | change the ownership of folder 
  file:
    path: "{{ lvm_mntp }}"
    state: directory
    owner: root
    group: "{{ project_code }}_vmuser.eresearch"
    recurse: yes
    mode: "g+s"
  become: yes


- name: permission | set ACLs to ensure that the group has always the right permissions on files and folders
  acl:
    path: "{{ lvm_mntp }}"
    entity: "{{ project_code }}_vmuser.eresearch"
    etype: group
    recursive: yes
    default: no
    permissions: rwx
    state: present
  become: yes

- name: permission | set ACLs to ensure that the group has always the right permissions on files and folders
  acl:
    path: "{{ lvm_mntp }}"
    entity: "{{ project_code }}_vmuser.eresearch"
    etype: group
    recursive: yes
    default: yes
    permissions: rwx
    state: present
  become: yes
  
