---
- name: repository | add x2go/stable (Ubuntu only, RHEL packages obtained from EPEL) 
  apt_repository:
    repo: "ppa:x2go/stable"
    state: present
    update_cache: true
  tags:
    - x2go-repository-add
  become: yes
  when: ansible_os_family == "Debian"

