- name: Set timezone to Pacific/Auckland
  timezone:
    name: Pacific/Auckland
    hwclock: UTC
  notify: restart crond
  become: yes

- name: ensure LDAP is installed
  apt:
    name: "chrony"
    state: present
    update-cache: yes
  become: yes

- name: Disable sytemd.timesync and ntp services
  service:
    name: "{{item}}"
    enabled: no
    masked: yes
    state: stopped
  with_item:
    - systemd-timesyncd
    - ntp
  become: yes

- name: Enable Chrony services
  service:
    name: chronyd
    enabled: no
  become: yes

- name: Ensure chronyd is active
  service:
    name: chronyd
    state: started
  become: yes

- name: install chrony.conf
  copy:
    src: files/chrony.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart chronyd
