---


- name: ensure config file is present
  file:
    path: /etc/profile
    state: file
  become: yes

- name: add http and https proxy to config file
  become: yes
  lineinfile:
    path: /etc/profile
    line: "{{ item }}"
  with_items:
    - 'export http_proxy="http://squid.auckland.ac.nz:3128/"'
    - 'export https_proxy="http://squid.auckland.ac.nz:3128/"'

- name: Ubuntu | add proxy setting for apt
  template:
    src: apt.conf.txt
    dest: /etc/apt/apt.conf.d/98proxy
  become: yes
  when: ansible_os_family == "Debian"
