---


- name: ensure config file is present
  file:
    path: /etc/profile
    state: file
  become: yes

- name: add proxy variables to config file
  become: yes
  lineinfile:
    path: /etc/profile
    line: "{{ item }}"
  with_items:
    - 'export http_proxy="http://squid.auckland.ac.nz:3128/"'
    - 'export https_proxy="http://squid.auckland.ac.nz:3128/"'
    - 'export ftp_proxy="http://squid.auckland.ac.nz:3128/"'
    - 'export no_proxy="localhost,127.0.0.1,localaddress,.auckland.ac.nz"'

- name: ensure config file is present
  file:
    path: /etc/environment
    state: file
  become: yes

- name: add proxy variable to config file
  become: yes
  lineinfile:
    path: /etc/environment
    line: "{{ item }}"
  with_items:
    - 'export http_proxy="http://squid.auckland.ac.nz:3128/"'
    - 'export https_proxy="http://squid.auckland.ac.nz:3128/"'
    - 'export ftp_proxy="http://squid.auckland.ac.nz:3128/"'
    - 'export no_proxy="localhost,127.0.0.1,localaddress,.auckland.ac.nz"'
    - 'export HTTP_PROXY="http://squid.auckland.ac.nz:3128/"'
    - 'export HTTPS_PROXY="http://squid.auckland.ac.nz:3128/"'
    - 'export FTP_PROXY="http://squid.auckland.ac.nz:3128/"'
    - 'export NO_PROXY="localhost,127.0.0.1,localaddress,.auckland.ac.nz"'

- name: ensure sudoers.local config file is present
  file:
    path: /etc/sudoers.local
    state: file
  become: yes

- name: keep proxy setting when sudo
  become: yes
  lineinfile:
    path: /etc/sudoers.local
    line: 'Defaults env_keep = "http_proxy https_proxy no_proxy"'

- name: Ubuntu | add proxy setting for apt
  template:
    src: apt.conf.txt
    dest: /etc/apt/apt.conf.d/98proxy
  become: yes
  when: ansible_os_family == "Debian"

- name: RHEL | add proxy setting for yum
  lineinfile:
    path: /etc/yum.conf
    line: "{{ item }}"
  with_items:
    - 'proxy=http://squid.auckland.ac.nz:3128'
  become: yes
  when: ansible_os_family == "RedHat"
