---
# tasks file for xrdp
- include: "{{ ansible_os_family }}.yml"

- name: Configure xRDP to run mate-desktop
  template:
    src: startwm.sh.j2
    dest: /etc/xrdp/startwm.sh
    owner: xrdp
    group: xrdp
    mode: 0755
    force: yes
  become: yes

- name: Configure 2FA for sudo users
  copy:
    src: /etc/pam.d/sshd 
    dest: /etc/pam.d/xrdp-sesman
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes

- name: Restart xRDP service
  service: 
    name: xrdp
    state: restarted
  become: yes

- name: Open RDP port (3389) on VM's firewall
  lineinfile:
    path: /etc/fw.local
    line: '3389 tcp 0.0.0.0/0'
  become: yes

- name: Run Puppet agent to enable firewall rule
  puppet:
  become: yes
